name: Test API
on:
  push:
    branches: master
  pull_request:
    branches: master
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 38.242.243.61
          username: kimang
          key: ${{ secrets.SSH_KEY }}
          #port: 1133
          script: |
            . ~/.nvm/nvm.sh
            whoami
            pwd
            ls
            cd devops-cadt-2-main
            git pull
            pm2 restart devops-test
